services:
  frontend:
    image: ghcr.io/no-to-mediocrity/tochka-frontend:latest
    restart: always
    networks: [app]
    environment:
      VITE_API_URL: /api
      VITE_API_VERSION: v0.0.2
      VITE_API_VERSION_NEW: v1

  backend:
    image: ghcr.io/no-to-mediocrity/tochka-backend:latest
    restart: always
    networks: [app]
    environment:
      DATABASE_NAME: "${DB_NAME}"
      DATABASE_USER: "${DB_USER}"
      DATABASE_PASSWORD: "${DB_PASSWORD}"
      DATABASE_HOST: postgres_db
      DATABASE_PORT: "5432"
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8000"
      development_mode: "${DEVELOPMENT_MODE}"
      frontend_url: "${FRONTEND_URL}"
    command: >
      bash -lc "
        alembic upgrade head &&
        uvicorn server:app --host 0.0.0.0 --port 8000
      "
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [app]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - frontend
      - backend
    networks: [app]
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"

volumes:
  postgres_data:

networks:
  app:
    driver: bridge
