version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: always
    networks:
      - app
    environment:
      VITE_API_URL=/api
      VITE_API_VERSION='v0.0.2'
      VITE_API_VERSION_NEW='v1'

  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: always
    networks:
      - app
      
networks:
  app:
