name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      #
      # Checkout frontend repo
      #
      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          repository: no-to-mediocrity/${{ vars.REPO_FRONT }}
          path: frontend
          ssh-key: ${{ secrets.FRONTEND_DEPLOY_KEY }}

      #
      # Checkout backend repo
      #
      - name: Checkout backend
        uses: actions/checkout@v4
        with:
          repository: no-to-mediocrity/${{ vars.REPO_BACK }}
          path: backend
          ssh-key: ${{ secrets.BACKEND_DEPLOY_KEY }}

      #
      # Login to GHCR
      #
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
            | docker login ghcr.io \
                -u ${{ github.actor }} \
                --password-stdin

      #
      # Build frontend
      #
      - name: Build frontend image
        run: |
          docker build \
            -t ghcr.io/no-to-mediocrity/tochkacrm-frontend:latest \
            ./frontend

      #
      # Build backend
      #
      - name: Build backend image
        run: |
          docker build \
            -t ghcr.io/no-to-mediocrity/tochkacrm-backend:latest \
            ./backend

      #
      # Push images
      #
      - name: Push frontend
        run: |
          docker push ghcr
