name: B Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.B_PK }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ vars.B_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh ${{ vars.B_USER }}@${{ vars.B_HOST }} << "EOF"
          if [ ! -d tochkacrm ]; then
            git clone git@github-base:no-to-mediocrity/tochka_crm.git tochkacrm
          else
            cd tochkacrm && git pull origin main 
          fi

          if [ ! -d frontend ]; then
            git clone git@github-frontend:no-to-mediocrity/${{ vars.REPO_FRONT }}.git frontend
          else
            cd frontend && git pull origin ${{ vars.REPO_FRONT_BRANCH }} && cd ..
          fi

          if [ ! -d backend ]; then
            git clone git@github-backend:no-to-mediocrity/${{ vars.REPO_BACK }}.git backend
          else
            cd backend && git pull origin main && cd ..
          fi
          
          # Build backend with Kaniko
          cd backend
          docker run --rm -v $(pwd):/workspace gcr.io/kaniko-project/executor:latest \
                  --dockerfile=Dockerfile \
                  --context=dir:///workspace \
                  --tarPath=/workspace/backend.tar
          docker load -i backend.tar
          cd ..
          
          # Same for frontend if needed
          cd frontend
          docker run --rm -v $(pwd):/workspace gcr.io/kaniko-project/executor:latest \
                  --dockerfile=Dockerfile \
                  --context=dir:///workspace \
                  --tarPath=/workspace/frontend.tar
          docker load -i frontend.tar
          cd ..

          docker compose -f docker-compose.yml up -d
          docker compose -f infra-compose.yml up -d --build
          EOF


