name: B Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ vars.B_PK }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ vars.B_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.B_NAME }}@${{ vars.B_HOST }} << 'EOF'
          cd /path/to/your/app || exit 1
          git pull origin main || exit 1
          docker compose up -d --build || exit 1
        EOF

